export const SIGNIN_REQUEST  = "@reducer/SIGNIN_REQUEST";
export const SIGNIN_SUCCESS = "@reducer/SIGNIN_SUCCESS";
export const SIGNIN_FAILED = "@reducer/SIGNIN_FAILED";

export const SIGNUP_REQUEST = "@reducer/SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "@reducer/SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "@reducer/SIGNUP_FAILED";

export const CREATE_PROJECT_REQUEST = "@reducer/CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS = "@reducer/CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAILED = "@reducer/CREATE_PROJECT_FAILED";

export const FETCH_ARR_PROJECT_CATEGORY_REQUEST = '@reducer/FETCH_ARR_PROJECT_CATEGORY_REQUEST';
export const FETCH_ARR_PROJECT_CATEGORY_SUCCESS = '@reducer/FETCH_ARR_PROJECT_CATEGORY_SUCCESS';
export const FETCH_ARR_PROJECT_CATEGORY_FAILED = '@reducer/FETCH_ARR_PROJECT_CATEGORY_FAILED';

export const GET_ALL_PROJECT_REQUEST  = "@reducer/GET_ALL_PROJECT_REQUEST";
export const GET_ALL_PROJECT_SUCCESS = "@reducer/GET_ALL_PROJECT_SUCCESS";
export const GET_ALL_PROJECT_FAILED = "@reducer/GET_ALL_PROJECT_FAILED";